/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.sc.view.inserir;

import br.senai.sc.controller.FuncionarioController;
import br.senai.sc.model.negocio.Funcionario;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pati
 */
public class InserirFuncionarioGUI extends javax.swing.JFrame {

    private DefaultTableModel modelo = new DefaultTableModel();
    private int linhaSelecionada;

    public InserirFuncionarioGUI(DefaultTableModel modelo) {
        this.modelo = modelo;
        initComponents();
        setLocationRelativeTo(null);
    }

    public InserirFuncionarioGUI(DefaultTableModel modelo, int linhaSelecionada, int idFuncionario) {
        this.modelo = modelo;
        this.linhaSelecionada = linhaSelecionada;

        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelFuncionario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txNomeFuncionario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txTelefoneFuncionario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txEmailFuncionario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txCpfFuncionario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txRgFuncionario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txDtCadastroFuncionario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbCargoFuncionario = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        txCtpsFuncionario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txSalarioFuncionario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txDtAdmissao = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txDtRecisao = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        txDtNascimentoFuncionario = new javax.swing.JTextField();
        txLoginFuncionario = new javax.swing.JTextField();
        txEnderecoFuncionario = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txIdFuncionario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        painelFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        painelFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Funcionário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N
        painelFuncionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("Nome:  ");
        painelFuncionario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 43, 123, -1));

        txNomeFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNomeFuncionarioActionPerformed(evt);
            }
        });
        painelFuncionario.add(txNomeFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 284, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Telefone:  ");
        painelFuncionario.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 69, 123, -1));
        painelFuncionario.add(txTelefoneFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 68, 284, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Email:  ");
        painelFuncionario.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 95, 123, -1));
        painelFuncionario.add(txEmailFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 94, 284, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Cpf:  ");
        painelFuncionario.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 121, 123, -1));
        painelFuncionario.add(txCpfFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 120, 284, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setText("Rg:  ");
        painelFuncionario.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 147, 123, -1));
        painelFuncionario.add(txRgFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 146, 284, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setText("Endereço:  ");
        painelFuncionario.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 173, 123, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setText("Dt Nascimento:  ");
        painelFuncionario.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 200, 112, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setText("Login Funcionário:  ");
        painelFuncionario.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 226, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setText("Data Cadastro:  ");
        painelFuncionario.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 252, 119, -1));
        painelFuncionario.add(txDtCadastroFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 251, 284, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel10.setText("Cargo:  ");
        painelFuncionario.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 280, 121, -1));

        cbCargoFuncionario.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cbCargoFuncionario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Designer", "Auxiliar de Corte", "Auxiliar de ficha técnica", "Estagiário(a)", "Serviços Gerais" }));
        cbCargoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCargoFuncionarioActionPerformed(evt);
            }
        });
        painelFuncionario.add(cbCargoFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 277, 284, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel11.setText("Ctps:  ");
        painelFuncionario.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 306, 121, -1));

        txCtpsFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCtpsFuncionarioActionPerformed(evt);
            }
        });
        painelFuncionario.add(txCtpsFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 305, 284, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel12.setText("Salário:  ");
        painelFuncionario.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 332, 121, -1));
        painelFuncionario.add(txSalarioFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 331, 284, -1));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel13.setText("Dt Admissão:  ");
        painelFuncionario.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 358, 121, -1));
        painelFuncionario.add(txDtAdmissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 357, 284, -1));

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel14.setText("Dt Recisão:  ");
        painelFuncionario.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 384, 111, -1));
        painelFuncionario.add(txDtRecisao, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 383, 284, -1));

        btSalvar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btSalvar.setForeground(new java.awt.Color(102, 102, 102));
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        painelFuncionario.add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 440, -1, 49));

        btExcluir.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btExcluir.setForeground(new java.awt.Color(102, 102, 102));
        btExcluir.setText("Excluir");
        painelFuncionario.add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 440, -1, 49));

        txDtNascimentoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDtNascimentoFuncionarioActionPerformed(evt);
            }
        });
        painelFuncionario.add(txDtNascimentoFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 199, 284, -1));
        painelFuncionario.add(txLoginFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 225, 284, -1));
        painelFuncionario.add(txEnderecoFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 172, 284, -1));

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel15.setText("Id Funcionário:  ");
        painelFuncionario.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));
        painelFuncionario.add(txIdFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 280, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txNomeFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNomeFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNomeFuncionarioActionPerformed

    private void txCtpsFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCtpsFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCtpsFuncionarioActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Funcionario fun = new Funcionario();
        fun.setNome(txNomeFuncionario.getText());
        fun.setTelefone(txTelefoneFuncionario.getText());
        fun.setEmail(txEmailFuncionario.getText());
        fun.setCpf(txCpfFuncionario.getText());
        fun.setRg(txRgFuncionario.getText());
        fun.setEndereco(txEnderecoFuncionario.getText());
        try {
            String data = txDtNascimentoFuncionario.getText();

            fun.setDtNascimento(new SimpleDateFormat("dd/mm/yyyy").parse(data));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Data incorreta" + ex);
        }
        fun.setLogin(txLoginFuncionario.getText());
        try {
            String data = txDtCadastroFuncionario.getText();

            fun.setDtCadastro(new SimpleDateFormat("dd/mm/yyyy").parse(data));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Data incorreta" + ex);
        }
        fun.setCargo(cbCargoFuncionario.getSelectedItem().toString());
        fun.setCtps(txCtpsFuncionario.getText());
        fun.setSalario(Double.parseDouble(txSalarioFuncionario.getText()));
        try {
            String data = txDtAdmissao.getText();

            fun.setDtAdmissao(new SimpleDateFormat("dd/mm/yyyy").parse(data));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Data incorreta" + ex);
        }
        try {
            String data = txDtRecisao.getText();

            fun.setDtRecisao(new SimpleDateFormat("dd/mm/yyyy").parse(data));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Data incorreta" + ex);
        }

        FuncionarioController fc = new FuncionarioController();
        if (!(txIdFuncionario.getText().equals("")
                || (txIdFuncionario.getText().equals(null)))) {
            fun.setNome(txIdFuncionario.getText());

            fc.update(fun);
            modelo.removeRow(linhaSelecionada);
            modelo.addRow(new Object[]{fun.getNome(), fun.getTelefone(), fun.getEmail()});
            this.dispose();
        }else{
            fc.inserir(fun);
        }
        txIdFuncionario.setText(null);
            




    }//GEN-LAST:event_btSalvarActionPerformed

    private void cbCargoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCargoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCargoFuncionarioActionPerformed

    private void txDtNascimentoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDtNascimentoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDtNascimentoFuncionarioActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox cbCargoFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel painelFuncionario;
    private javax.swing.JTextField txCpfFuncionario;
    private javax.swing.JTextField txCtpsFuncionario;
    private javax.swing.JTextField txDtAdmissao;
    private javax.swing.JTextField txDtCadastroFuncionario;
    private javax.swing.JTextField txDtNascimentoFuncionario;
    private javax.swing.JTextField txDtRecisao;
    private javax.swing.JTextField txEmailFuncionario;
    private javax.swing.JTextField txEnderecoFuncionario;
    private javax.swing.JTextField txIdFuncionario;
    private javax.swing.JTextField txLoginFuncionario;
    private javax.swing.JTextField txNomeFuncionario;
    private javax.swing.JTextField txRgFuncionario;
    private javax.swing.JTextField txSalarioFuncionario;
    private javax.swing.JTextField txTelefoneFuncionario;
    // End of variables declaration//GEN-END:variables
}
